environment: development # development | production
server:
  port: 8080
  read_timeout: 10 # seconds
  write_timeout: 10 # seconds
  idle_timeout: 60 # seconds
database:
  connect_timeout: 10 # seconds
  user: postgres
  host: localhost
  port: 5432
  dbname: shift_manager_db
initial_admin:
  username: admin
  full_name: 管理员
jwt:
  expiration: 336 # hours

